config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  root to: "homes#top"
  get '/about' => "homes#about", as: "about"

  resources :genres, only: [:new, :index, :show, :edit, :create, :destroy, :update] do
    resources :books, only: [:edit, :create, :destroy, :update]
  end

  resources :equipments, only: [:index, :create, :edit, :update, :destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :name, presence: true

  has_many :books, dependent: :destroy
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def new
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to genre_path(@genre)
    else
      render :new
    end
  end

  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def show
    @genres = Genre.all
    @genre = Genre.find(params[:id])
    @books = @genre.books
    @book = Book.new
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to genre_path(@genre.id)
     else
      render :edit
     end
  end

  def destroy
    @genre = Genre.find(params[:id])
    @genre.destroy
    redirect_to genres_path
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/_list.html.erb
<ul>
 <% genres.each do |genre| %>
   <li><%= link_to genre.name, genre_path(genre.id) %></li>
 <% end %>
<ul>

app/views/genres/edit.html.erb
<h1>Genres#edit</h1>
<p>Find me in app/views/genres/edit.html.erb</p>

<% if @genre.errors.any? %>
  <%= @genre.errors.count %>件のエラーが発生しました
  <ul>
    <% @genre.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @genre do |f| %>

  <h4>ジャンル名</h4>
  <%= f.text_field :name %>
  
  <%= f.submit '保存' %>

  <%= link_to "Destroy", genre_path(@genre.id), method: :delete, "data-confirm" => "Are you sure?" %>
  
<% end %>

app/views/genres/index.html.erb
<h1>Genres#index</h1>
<p>Find me in app/views/genres/index.html.erb</p>


 <h4>name</h4>
 <ul>
  <% @genres.each do |genre| %>
    <li><%= link_to genre.name, genre_path(genre) %></li>
  <% end %>
 <ul>

 <% if @genre.errors.any? %>
  <%= @genre.errors.count %>件のエラーが発生しました
  <ul>
    <% @genre.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @genre do |f| %>
  <h4>ジャンル名</h4>
  <%= f.text_field :name %>
	
  <%= f.submit '投稿' %>
<% end %>

app/views/genres/new.html.erb
<h1>Genres#new</h1>
<p>Find me in app/views/genres/new.html.erb</p>

<% if @genre.errors.any? %>
  <%= @genre.errors.count %>件のエラーが発生しました
  <ul>
    <% @genre.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @genre do |f| %>
  <h4>ジャンル名</h4>
  <%= f.text_field :name %>
	
  <%= f.submit '投稿' %>
<% end %>

app/views/genres/show.html.erb
<h1>Genres#show</h1>
<p>Find me in app/views/genres/show.html.erb</p>

<h2>ジャンル名：<%= @genre.name %></h2>

<%= render 'list', genres: @genres %>

<table>
  
<thead>
 <tr>
  <th>整理番号</th>
  <th>タイトル</th>
  <th>著者</th>
  <th>出版社</th>
  <th>購入日</th>
  <th>備考</th>
  <% if admin_signed_in? %>
    <th colspan = "1"></th>
  <% end %>
 </tr>
</thead>

<tbody>
 <% @books.each do |book| %>
  <tr>
   <td><%= book.number %></td>
   <td><%= book.title %></td>
   <td><%= book.author %></td>
   <td><%= book.publisher %></td>
   <td><%= book.date %></td>
   <td><%= book.note %></td>
   <% if admin_signed_in? %>
    <td><%= link_to "編集", edit_genre_book_path(@genre.id, book.id) %></td>
   <% end %>
  </tr>
 <% end %>
</tbody>

</table>

<% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: [@genre, @book] do |f| %>
  <h4>整理番号</h4>
  <%= f.text_field :number %>

  <h4>タイトル</h4>
  <%= f.text_field :title %>

  <h4>著者</h4>
  <%= f.text_field :author %>

  <h4>出版社</h4>
  <%= f.text_field :publisher %>

  <h4>購入日</h4>
  <%= f.text_field :date %>

  <h4>備考</h4>
  <%= f.text_field :note %>
	
  <%= f.submit '投稿' %>
<% end %>