config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  root to: "homes#top"
  get '/about' => "homes#about", as: "about"

  resources :genres, only: [:new, :index, :show, :edit, :create, :destroy, :update] do
    resources :books, only: [:edit, :create, :destroy, :update]
  end

  resources :equipments, only: [:index, :create, :edit, :update, :destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/equipment.rb
class Equipment < ApplicationRecord
  has_one_attached :image

  validates :name, presence: true
end

app/controllers/equipments_controller.rb
class EquipmentsController < ApplicationController
  def index
    @equipments = Equipment.all
    @equipment = Equipment.new
  end

  def create
    @equipment = Equipment.new(equipment_params)
    if @equipment.save
      redirect_to equipments_path
    else
      @equipments = Equipment.all
      render :index
    end
  end

  def edit
    @equipment = Equipment.find(params[:id])
  end

  def update
    @equipment = Equipment.find(params[:id])
    if @equipment.update(equipment_params)
      redirect_to equipments_path
    else
      render :edit
    end
  end

  def destroy
    @equipment = Equipment.find(params[:id])
    @equipment.destroy
    redirect_to equipments_path
  end

  private
  def equipment_params
    params.require(:equipment).permit(:name, :image, :detail)
  end
end

app/helpers/equipments_helper.rb
module EquipmentsHelper
end

app/views/equipments/edit.html.erb
<h1>Equipments#edit</h1>
<p>Find me in app/views/equipments/edit.html.erb</p>

<% if @equipment.errors.any? %>
  <%= @equipment.errors.count %>件のエラーが発生しました
  <ul>
    <% @equipment.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @equipment do |f| %>
  <h4>設備名</h4>
  <%= f.text_field :name %>

  <h4>詳細</h4>
  <%= f.text_field :detail %>	
  <%= f.submit '投稿' %>
<% end %>

<h3><%= link_to "Destroy", equipment_path(@equipment.id), method: :delete, "data-confirm" => "Are you sure?" %></h3>

app/views/equipments/index.html.erb
<h1>Equipments#index</h1>
<p>Find me in app/views/equipments/index.html.erb</p>

<table>
  <tbody>
    <% @equipments.each do |equipment| %>
      <tr>
        <td><%= equipment.name %></td>
        <td><%= equipment.detail %></td>
        <td>
          <% if equipment.image.attached? %>
            <%= image_tag equipment.image, size: "200x200" %>
          <% else %>
            <%= image_tag 'no_image', size: "200x200" %>
          <% end %>
        <% if admin_signed_in? %>
          <td><%= link_to "編集", edit_equipment_path(equipment.id) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
<table>

<% if @equipment.errors.any? %>
  <%= @equipment.errors.count %>件のエラーが発生しました
  <ul>
    <% @equipment.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @equipment, url: equipments_path do |f| %>
  <h4>設備名</h4>
  <%= f.text_field :name %>

  <h4>画像</h4>
  <%= f.file_field :image, accept: "image/*" %>

  <h4>詳細</h4>
  <%= f.text_field :detail %>	
  <%= f.submit '投稿' %>
<% end %>