config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  root to: "homes#top"
  get '/about' => "homes#about", as: "about"

  resources :genres, only: [:new, :index, :show, :edit, :create, :destroy, :update] do
    resources :books, only: [:edit, :create, :destroy, :update]
  end

  resources :equipments, only: [:index, :create, :edit, :update, :destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :author, presence: true
  validates :publisher, presence: true

  belongs_to :genre
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def create
    @genre = Genre.find(params[:genre_id])
    @book = @genre.books.new(book_params)
    @book.genre_id = @genre.id
    if @book.save
      redirect_to genre_path(@genre.id)
    else
      render "genres/show.html.erb"
    end
  end

  def edit
    @book = Book.find(params[:id])
    @genre = @book.genre
  end
  
  def update
    @book = Book.find(params[:id])
    @genre = @book.genre
    if @book.update(book_params)
      redirect_to genre_path(@genre.id)
    else
      render :edit
    end
  end

  def destroy
    Book.find(params[:id]).destroy
    redirect_to genre_path(params[:genre_id])
  end

  private
  def book_params
    params.require(:book).permit(:number, :title, :author, :publisher, :date, :note, :genre_id)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<h1>Books#edit</h1>
<p>Find me in app/views/books/edit.html.erb</p>

<% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: [@genre, @book] do |f| %>
  <h4>整理番号</h4>
  <%= f.text_field :number %>

  <h4>タイトル</h4>
  <%= f.text_field :title %>

  <h4>著者</h4>
  <%= f.text_field :author %>

  <h4>出版社</h4>
  <%= f.text_field :publisher %>

  <h4>購入日</h4>
  <%= f.text_field :date %>

  <h4>備考</h4>
  <%= f.text_field :note %>
	
  <%= f.submit '投稿' %>
<% end %>

<h3><%= link_to "Destroy", genre_book_path(@genre, @book.id), method: :delete, "data-confirm" => "Are you sure?" %></h3>